### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by xunkaixin** [Natsu-Akatsuki/RangeNetTrt8#1]
非常感谢共享

1、TensorRT 版本 
      nvinfer1::BuilderFlag::kPREFER_PRECISION_CONSTRAINTS 在8.2.3.0版本中有定义  8.0.0.3中没有
2、onnx 模型下载路径
    http://www.ipb.uni-bonn.de/html/projects/bonnetal/lidar/semantic/predictions/darknet53.tar.gz 是数据 不是模型地址
3、执行出错
================================================================================
Setting verbosity to: false
Trying to open model
read engine file /home/qkj/projects/auto_driving/catkin_ws/RangeNetTrt8/model/darknet53/model.trt failed
Could not deserialize TensorRT engine. 
Generating from sratch... This may take a while...
Trying to serialize engine and save to : /home/qkj/projects/auto_driving/catkin_ws/RangeNetTrt8/model/darknet53/model.trt for next run
Segmentation fault (core dumped)

**Comment by Natsu-Akatsuki** [comment]
感谢您的反馈，现在就改正
1. 8.0.0.3可以使用kSTRICT_TYPES，Native PC的版本应该跟docker都是8.2.3.0的。
2. 大意了（扶额.jpg），不过你应该你应该知道在哪里改了（现在就去改README）。
3. 信息量太少了，现在情况是优化预测模型那里出问题，可能是代码的锅，也可能是环境的锅。你试一下trtexec CLI能不能直接生成engine。

**Comment by Natsu-Akatsuki** [comment]
:) 还有问题吗，欢迎反馈
