### ISSUE TITLE
onnx转trt

### ISSUE THREAD

**Issue by yuyaoliang** [Natsu-Akatsuki/RangeNetTrt8#12]
大佬您好，我看您在onnx转trt的时候有不同层的权值类型设置，这个应该是基于您自己的带有CRF的darknet53网络模型，我想问下如果我的darknet53网络模型不带CRF，应该怎么设置呢，我直接暴力的把这里注释掉后，效果会非常差，求指教
![2023-10-25 11-21-27屏幕截图](https://github.com/Natsu-Akatsuki/RangeNetTrt8/assets/61180826/f24de677-2118-421c-9d79-8d3d01b681cc)

**Comment by Natsu-Akatsuki** [comment]
1. 这个模型不是我的，是原仓库的模型。
2. 你注释了这里，也只是修改了对应层的权值策略，并不说你能去掉 CRF。
3. 原仓库的模型，你怎么知道它是用了 CRF ？

**Comment by yuyaoliang** [comment]
感谢大佬，解决了，是我自己数据没有做相应修改，与转trt这里没关系
