### ISSUE TITLE
Ihave three weight files. Do I need to merge these three weight files together first?

### ISSUE THREAD

**Issue by 1806610292** [Natsu-Akatsuki/RangeNetTrt8#13]
Thank you very much for your work. I've trained using the Python source code of Rangenet++, and I now have three weight files. Do I need to merge these three weight files together first?

**Comment by Natsu-Akatsuki** [comment]
Thanks for your try.

I have not tried the training phase and used the generated model file (do you mean the file `backbone`, `segmentation_decoder`, `segmentation_head`?) to construct the onnx-format model file.

May be this issue would help you: https://github.com/PRBonn/lidar-bonnetal/issues/32

**Comment by 1806610292** [comment]
> Thanks for your try.
> 
> I have not tried the training phase and used the generated model file (do you mean the file `backbone`, `segmentation_decoder`, `segmentation_head`?) to construct the onnx-format model file.
> 
> May be this issue would help you: [PRBonn/lidar-bonnetal#32](https://github.com/PRBonn/lidar-bonnetal/issues/32)

I followed your advice and have resolved the issue. Thank you very much！

**Comment by Natsu-Akatsuki** [comment]
Get. Valuable feedback.
