### ISSUE TITLE
Segmentation fault Error

### ISSUE THREAD

**Issue by smileyr99** [Natsu-Akatsuki/RangeNetTrt8#16]
First of all, thank you for the good code.
Running the robag file works very well, but running ./demo to segment the pcd file causes the following error.
Do you know the solution?

My current environment is as follows.
cuda: 11.8
cudnn: 8.6.0
tensorrt: 8.6.0.12

![Screenshot from 2024-02-05 18-13-49](https://github.com/Natsu-Akatsuki/RangeNetTrt8/assets/87894946/a04cef92-1f47-4584-95be-87617b62a59d)

**Comment by Natsu-Akatsuki** [comment]
Do you use Ubuntu22.04？If yes, then SIGSEGV will happen in the pcl_viewer.  https://github.com/Natsu-Akatsuki/RangeNetTrt8/blob/main/src/network/netTensorRT.cpp#L161

**Comment by smileyr99** [comment]
No, I'm using Ubuntu 20.04.
Can the pcl_viewer issue also occur on Ubuntu 20.04?

**Comment by smileyr99** [comment]
> Do you use Ubuntu22.04？If yes, then SIGSEGV will happen in the pcl_viewer. https://github.com/Natsu-Akatsuki/RangeNetTrt8/blob/main/src/network/netTensorRT.cpp#L161

No, I'm using Ubuntu 20.04.
Can the pcl_viewer issue also occur on Ubuntu 20.04?

**Comment by Natsu-Akatsuki** [comment]
Actually, in my experiment, the issue caused by pcl_viewer did not occur in Ubuntu 20.04. You should use gdb/lldb to locate the bug.

**Comment by Natsu-Akatsuki** [comment]
@smileyr99 It seems that you use non-KITTI point cloud instead of provided demo. Does your point cloud obey RangeNet point cloud input requirement?

**Comment by smileyr99** [comment]
I couldn't download the provided model and data files, so I converted a KITTI ROS bag file into a PCD file and used that instead.
Where can I find the requirements for the RangeNet Point Cloud in terms of the PCD file?

Can you send me an example file containing the model and data via email?
My email address is yr2819@dgu.ac.kr. 
Thank you.

**Comment by Natsu-Akatsuki** [comment]
1. See [README](https://github.com/Natsu-Akatsuki/RangeNetTrt8?tab=readme-ov-file#install), we have provided the download link through Baidu Netdisk.
2. The data file and model file has been sent into your email.
3. Naturally, the PCD file, that you export from the KITTI ROS bad file is legal. The point cloud input requirement seems to be satisfied.
4. **According to your latest statement and previous log, the solution is to use our provided model file to generate the engine.**

**Comment by Natsu-Akatsuki** [comment]
Try git pull. The latest repository has supported TensorRT 8.6.
