### ISSUE TITLE
关于RTX4060Laptop、CUDA11.3、cudnn8.6.0、Tensorrt8.4.15、libtorch1.13从onnx到处trt文件报错terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by NirvanaDragon** [Natsu-Akatsuki/RangeNetTrt8#17]

**Comment by Natsu-Akatsuki** [comment]
请提供完整的报错信息日志，而非单纯的结果

**Comment by NirvanaDragon** [comment]
当我按照CUDA11.3、cudnn8.6.0、Tensorrt8.4.15环境在ubuntu20.04运行后，发现用onnx生成trt文件会报如下错误
![图片](https://github.com/Natsu-Akatsuki/RangeNetTrt8/assets/117355124/a455f5b0-8a4f-4ef4-b688-1a6057ecf1ad)
网上说是由于Tensorrt的版本较低导致的，于是我更换到最新版Tensorrt8.6.1.6，出现如下错误的推理结果
![图片](https://github.com/Natsu-Akatsuki/RangeNetTrt8/assets/117355124/561fcac9-ce79-4e6a-acf7-8d819db799de)
![图片](https://github.com/Natsu-Akatsuki/RangeNetTrt8/assets/117355124/866f9b61-358d-4b5c-af8d-9d6f95f65ff9)
您能帮忙看看吗

**Comment by Natsu-Akatsuki** [comment]
1. 关于更高版本的预测异常问题。TensorRT8.6还没进行测试。不同 TensorRT版本有不同的权值溢出处理方案。可参考https://github.com/Natsu-Akatsuki/RangeNetTrt8/blob/main/src/network/netTensorRT.cpp#L283修改层数。
2. 关于40系列显卡中的模型转换异常问题。感谢测试，后续有时间，我这边将进行复现和测试。

**Comment by Natsu-Akatsuki** [comment]
可

**Comment by NirvanaDragon** [comment]
您好，我将int start调整到233，并将FP16改成config->setFlag(nvinfer1::BuilderFlag::kTF32);得到如下结果
![图片](https://github.com/Natsu-Akatsuki/RangeNetTrt8/assets/117355124/d19a9ebb-3689-45d9-a2b0-0b089dc0d4ec)
当我将其应用到其他点云文件中，发现效果很差，如下所示
![图片](https://github.com/Natsu-Akatsuki/RangeNetTrt8/assets/117355124/7625ef3b-bd2a-49b9-b4f4-1082debe2dd6)
这代表rangenet的问题还是我导出模型的问题呢

**Comment by Natsu-Akatsuki** [comment]
你这个点云文件是否满足模型的输入要求：进行强度归一化了吗，点云是否是64线？

**Comment by Natsu-Akatsuki** [comment]
1. 40系列显卡，使用 TensorRT 8.4.1.5（i.e., 8.4 GA）和 8.4.2.4（i.e., 8.4 Update GA 1） 可复现如下报错，报错原因即字面意思。
> [02/22/2024-22:31:03] [E] 1: [caskBuilderUtils.cpp::trtSmToCaskCCV::548] Error Code 1: Internal Error (Unsupported SM: 0x809)
[02/22/2024-22:31:03] [E] 2: [builder.cpp::buildSerializedNetwork::636] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to build tensorrt engine
2. 根据 TensorRT 的官方文档 [Support Matrix](https://docs.nvidia.com/deeplearning/tensorrt/archives/index.html) 说明，只有 8.5.1+的版本才开始支持 89架构（即40系列显卡），但实测 8.4.3.1 （i.e., 8.4 Update GA 2）也可以正常运行。但建议还是使用官方推荐的 TensorRT 8.5+版本，或有专门针对89架构的优化。

**Comment by Natsu-Akatsuki** [comment]
> 您好，我将int start调整到233，并将FP16改成config->setFlag(nvinfer1::BuilderFlag::kTF32);得到如下结果 ![图片](https://private-user-images.githubusercontent.com/117355124/306988100-d19a9ebb-3689-45d9-a2b0-0b089dc0d4ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTIzOTMsIm5iZiI6MTcwODY5MjA5MywicGF0aCI6Ii8xMTczNTUxMjQvMzA2OTg4MTAwLWQxOWE5ZWJiLTM2ODktNDVkOS1hMmIwLTBiMDg5ZGMwZDRlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMjQxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzhmZjZhOWIyY2JhODA0NWZiNDBiZmUzNzc2NzUwNjk5NGFmYmUwYTg0MDQzMGM1MjA1NGM5YjE0OTQ3YWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ef-SDjBXzp1xDGO2L9rsOAqP_rRJWzbLtA-FblVGRi4) 当我将其应用到其他点云文件中，发现效果很差，如下所示 ![图片](https://private-user-images.githubusercontent.com/117355124/306988578-7625ef3b-bd2a-49b9-b4f4-1082debe2dd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTIzOTMsIm5iZiI6MTcwODY5MjA5MywicGF0aCI6Ii8xMTczNTUxMjQvMzA2OTg4NTc4LTc2MjVlZjNiLWJkMmEtNDliOS1iNGY0LTEwODJkZWJlMmRkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMjQxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2FhZDAwNmU2ODhiODI4Y2JlZjA3ODAyYjA4ZmRlNzQ3MDc5YmFhMDNlM2IzMDM0NjdmNWFlYTcwYjQwOGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QvyRXOD6E0n4kRBsiN09F4EIqvRp5J0DfZlxQ_17ahA) 这代表rangenet的问题还是我导出模型的问题呢

提一嘴，你这边最终起作用的是 config->setFlag(nvinfer1::BuilderFlag::kTF32); 调 start 是配合 FP16 的

**Comment by NirvanaDragon** [comment]
> > 您好，我将int start调整到233，并将FP16改成config->setFlag(nvinfer1::BuilderFlag::kTF32);得到如下结果 ![图片](https://private-user-images.githubusercontent.com/117355124/306988100-d19a9ebb-3689-45d9-a2b0-0b089dc0d4ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTIzOTMsIm5iZiI6MTcwODY5MjA5MywicGF0aCI6Ii8xMTczNTUxMjQvMzA2OTg4MTAwLWQxOWE5ZWJiLTM2ODktNDVkOS1hMmIwLTBiMDg5ZGMwZDRlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMjQxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzhmZjZhOWIyY2JhODA0NWZiNDBiZmUzNzc2NzUwNjk5NGFmYmUwYTg0MDQzMGM1MjA1NGM5YjE0OTQ3YWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ef-SDjBXzp1xDGO2L9rsOAqP_rRJWzbLtA-FblVGRi4) 当我将其应用到其他点云文件中，发现效果很差，如下所示 ![图片](https://private-user-images.githubusercontent.com/117355124/306988578-7625ef3b-bd2a-49b9-b4f4-1082debe2dd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTIzOTMsIm5iZiI6MTcwODY5MjA5MywicGF0aCI6Ii8xMTczNTUxMjQvMzA2OTg4NTc4LTc2MjVlZjNiLWJkMmEtNDliOS1iNGY0LTEwODJkZWJlMmRkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMjQxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2FhZDAwNmU2ODhiODI4Y2JlZjA3ODAyYjA4ZmRlNzQ3MDc5YmFhMDNlM2IzMDM0NjdmNWFlYTcwYjQwOGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QvyRXOD6E0n4kRBsiN09F4EIqvRp5J0DfZlxQ_17ahA) 这代表rangenet的问题还是我导出模型的问题呢
> 
> 提一嘴，你这边最终起作用的是 config->setFlag(nvinfer1::BuilderFlag::kTF32); 调 start 是配合 FP16 的

嗯嗯。谢谢指导
