### ISSUE TITLE
How to install cuda 11.3 in ubuntu 22.04

### ISSUE THREAD

**Issue by smileyr99** [Natsu-Akatsuki/RangeNetTrt8#18]
Hello, and thank you for providing excellent code.

I'm currently trying to conduct tests on Ubuntu 22.04, and I have a question regarding the CUDA version, which is set to 11.3. 
As of my knowledge cutoff date in January 2022, CUDA 11.3 was available up to Ubuntu 20.04. 
I'm curious about how you installed version 11.3 on Ubuntu 22.04. Thank you.

**Comment by Natsu-Akatsuki** [comment]
Use [runfile](https://developer.nvidia.com/cuda-11-3-1-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=runfile_local).

The 20.04 installer can be used in 22.04 as well.

![image](https://github.com/Natsu-Akatsuki/RangeNetTrt8/assets/47175732/2f766af8-d940-4f74-a5d4-81a18fc88362)

**Comment by smileyr99** [comment]
> Use [runfile](https://developer.nvidia.com/cuda-11-3-1-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=runfile_local).
> 
> The 20.04 installer can be used in 22.04 as well.
> 
> ![image](https://private-user-images.githubusercontent.com/47175732/310140148-2f766af8-d940-4f74-a5d4-81a18fc88362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTcwNDQsIm5iZiI6MTcwOTY5Njc0NCwicGF0aCI6Ii80NzE3NTczMi8zMTAxNDAxNDgtMmY3NjZhZjgtZDk0MC00Zjc0LWE1ZDQtODFhMThmYzg4MzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAzNDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YWFhN2M4M2FjNjZjMjMzMTBjM2MzMjIxMDA3ZWI4YjViNTY0MWQ5OWNmNjUzOWE0NGMxZThiNWI1NDI2YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v3KGMQtqUDkCAz8s-f1ntkxocA_1C_Tvt-PuV2e-ICc)

I see, thank you very much!! I appreciate your help.

**Comment by Natsu-Akatsuki** [comment]
Fine. I will close the issue.
