### ISSUE TITLE
ROS2 foxy

### ISSUE THREAD

**Issue by smileyr99** [Natsu-Akatsuki/RangeNetTrt8#22]
Is it possible to operate on ROS2 foxy?
I'm trying to run it on Ubuntu 20.04ros2 foxy.
Is it possible to change ros logic?

**Comment by Natsu-Akatsuki** [comment]
![image](https://github.com/user-attachments/assets/86167311-1240-4b7b-b699-67d7ea1c4b5f)

**Comment by smileyr99** [comment]
It's written in ROS2 Humble, so I didn't know if I could use it with Fox.
Thank you so much for your quick response.

**Comment by Natsu-Akatsuki** [comment]
As far as I know, the differences between foxy and humble cause few effect to this project.
