### ISSUE TITLE
RangeNetTrt8/ops/project_kernel.cu(3): error: A __device__ variable cannot be marked constexpr

### ISSUE THREAD

**Issue by mengdejiang** [Natsu-Akatsuki/RangeNetTrt8#4]

**Comment by Natsu-Akatsuki** [comment]
你好根据[API](https://stackoverflow.com/questions/71648859/why-the-device-variable-cant-be-marked-as-constexpr)的说明，估摸你使用了非推荐的cuda版本，我们这里要求使用cuda11.4+
