### ISSUE TITLE
运行效果问题请教

### ISSUE THREAD

**Issue by ArilliaBook** [Natsu-Akatsuki/RangeNetTrt8#5]
环境：ubuntu18.04, 其余cuda、cudnn、tesorrt与推荐相同
修改处：
1.将
#include <pcl/io/pcd_io.h>
改为了
#include <pcl/point_cloud.h>
#include<fstream>  
2.由于infer.cpp报error:loadPCDfile非pcl成员，将infer删除后编译完成

问题：
1.在ROS下正确的运行效果是在rviz中生成连续的语义分割点云吗？我在自己电脑上运行两个launch文件后rviz无输出，弹出3D_viewer窗口显示单帧语义点云，关闭后又显示下一帧语义点云。
2.infer.cpp是否是该项目必须文件？是否有解决pcl报错的方法？

感恩~

**Comment by Natsu-Akatsuki** [comment]
1. https://github.com/Natsu-Akatsuki/RangeNetTrt8/blob/master/src/netTensorRT.cpp#L162。这种情况下，主要是把这里宏定义设置为1，设置为0就能避免这种情况。
2. 不是，只是个demo，输入单帧点云，输出语义点云。可以删除。关于pcl报错的话，我需要复现一下，wait.

**Comment by ArilliaBook** [comment]
感谢！我去调试一下，如果有问题我会再反馈！

**Comment by ArilliaBook** [comment]
有个小问题想请教一下，该项目输出的时候是把label转换成rgb值从而在ROS实现分割效果的对吧？那点云分割后输出只保留了label的输出吗？貌似没找见probability输出的代码

**Comment by Natsu-Akatsuki** [comment]
1. 首先你之前这个关于：infer.cpp报error:loadPCDfile非pcl成员的问题，我这边暂时没有这个问题（ubuntu 20.04、22.04），18.04的话，你可以了解一下是不是你PCL版本没这个API，是不是需要换一个读取文件的API；
2. 关于没有概率信息的输出，具体是怎样的我忘了。应该是有的，我当时应该是改动了一下网络层，加了个topK，让他直接输出label信息了。详看 auto ktop_layer = network->addTopK(*network->getOutput(0), nvinfer1::TopKOperation::kMAX, 1, 2);

**Comment by ArilliaBook** [comment]
OK，感谢！
